# Generated by Django 4.2.7 on 2023-11-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('custom_user.useraccount',),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('custom_user.useraccount',),
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_student',
            new_name='is_client',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_teacher',
            new_name='is_owner',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(choices=[('CLIENT', 'client'), ('OWNER', 'owner')], default='OWNER', max_length=8),
        ),
    ]
